### ISSUE TITLE
Release version-1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-js#53]
# Overview

Tracking issue for https://github.com/frictionlessdata/jsontableschema-js/milestone/1

# Tasks

- [x] rebase on specs-v1
- [x] release ALPHA
---
- [x] `table.iter` should be a generator not callback-based!
- [x] reduce `infer`public API for now
- [x] add more `Table/Schema/Field` tests!
- [x] highlight `Table.schema` attribute (getter, readme)
- [ ] release
