### ISSUE TITLE
Fix Table class

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-js#58]
# Overview

stack reference - https://github.com/frictionlessdata/stack

# Tasks

- [ ] `Table` should support data with headers!
- [ ] `table.iter` should be a generator not callback-based (with callback it iterates over the whole table)?
- [ ] `table.iter(keyed/extended)` missed

**Comment by rufuspollock** [comment]
@roll as per #78 i think we should get rid of iter and just return a node object stream.

**Comment by roll** [comment]
@rufuspollock 
We should have a base interface which able to work both in node and browser. I suppose node object stream doesn't work in browser?

**Comment by rufuspollock** [comment]
@roll i think it would with browserify ...

**Comment by roll** [comment]
It seems there is only 2 options for now:
- `callback` as it's implemented now
- `Stream` from node.js

I've tried to find any proven way to parse csv with async loop output and it seems no libs for now. We could have `table.iter` as node only interface and implement `table.read` for browsers using lib like `papaparse` (should be easy without streaming)
